### ISSUE TITLE
Platform encoding is used for generated git.json/git.properties

### ISSUE THREAD

**Issue by frankbregulla1111** [git-commit-id/git-commit-id-maven-plugin#130]
Currently the plugin generates the git.json/git.properties file with the platform encoding of the build.
This can lead to problems when the file is later read at runtime in a different environment with a different encoding.

I would like to be able to specify the encoding with which this file is generated, so that the build is not platform dependent.

**Comment by rreitmann** [comment]
IMHO writing *.properties with UTF-8 is not correct since Java expects *.properties to be encoded in ISO-8859-1 (see http://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#load(java.io.InputStream))

We use spring-boot which uses your plugin to generate a git.properties and expose its contents through a REST endpoint. It reads the git.properties expecting ISO-8859-1.

**Comment by ktoso** [comment]
A bit sad that spring is not UTF-8 aware, but oh well...
Happy to accept configuration option in a PR if you'd like to contribute.

**Comment by ktoso** [comment]
I also think there's to separate things here.
For one thing, JSON is (spec: https://tools.ietf.org/html/rfc7159 ) required to be UTF so the git.json file definitely must be UTF,
properties we can think about I guess.

> 8.1.  Character Encoding
>    JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32.

**Comment by rreitmann** [comment]
Agreed, IMHO JSON **should** be UTF-8 whereas .properties **must** be ISO-8859-1

**Comment by ktoso** [comment]
Happy to accept a PR adding a setting for it.
