### ISSUE TITLE
Project erroneously marked as dirty when using jgit but clean with native git

### ISSUE THREAD

**Issue by notes-jj** [git-commit-id/git-commit-id-maven-plugin#440]
### Describe the bug
Bug #259 is still open. I'm seeing a as dirty reported workspace, even though it's clean.

I'm seeing this Error #259 with Version 3.0.1 and the error is not stable. So you could run the build multiple times and some of the builds are marked as dirty and some not.

I have javadoc plugin active and the javadoc are not ignored committed via git. When I run `git status --short` (see log below) I see temporary file changes flashing up. And for some javadoc files the javadoc plugin is not checking the before and after status in a right way and javadoc files get updated, even though the content wasn't changed. But after the build the workdir is always clean and not dirty.

I think it could be related to this error: 

- <https://github.com/palantir/gradle-git-version/issues/28>

Workaround is switching to native git.

### Steps to Reproduce

- Add Javadoc Plugin to a Project an do not git-ignore `apidocs` directory.
- Run `mvn clean install`
- git commit and push changes
- Run `mvn clean install`
- Check git.properties file for dirty status
- Do this multiple times if project is clean

```xml
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>3.1.1</version>
          <configuration>
            <reportOutputDirectory>${project.basedir}</reportOutputDirectory>
            <destDir>apidocs</destDir>
            <show>private</show>
            <notimestamp>true</notimestamp>
            <quiet>true</quiet>
            <bottom>Copyright Info</bottom>
          </configuration>
          <executions>
            <execution>
              <id>attach-javadocs</id>
              <goals>
                <goal>jar</goal>
              </goals>
            </execution>
          </executions>
        </plugin>

        <plugin>
          <groupId>pl.project13.maven</groupId>
          <artifactId>git-commit-id-plugin</artifactId>
          <version>3.0.1</version>
          <executions>
            <execution>
              <id>revision</id>
              <goals>
                <goal>revision</goal>
              </goals>
            </execution>
            <execution>
              <id>validateRevision</id>
              <goals>
                <goal>validateRevision</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <dateFormatTimeZone>UTC</dateFormatTimeZone>
            <generateGitPropertiesFile>true</generateGitPropertiesFile>
            <failOnNoGitDirectory>false</failOnNoGitDirectory>
            <!-- <useNativeGit>true</useNativeGit> -->
          </configuration>
        </plugin>
```

### Expected behavior
Workspace should be reported as not dirty

### Additional context
For reproducibility please provide the following:

- plugin version 3.0.1
- Java-Version:
``` text
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b32)
Java HotSpot(TM) Client VM (build 25.221-b32, mixed mode)
```
- Maven-Version
```
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
```
- Operating System: Windows 10 - 1903
- context maven is being executed: cmd and cygwin bash
- maven is being executed: `mvn clean install`

### git status

- Example of short periods of dirty workspace (command run by hand approx. every second)

```
$ git status --short

$ git status --short

$ git status --short
?? spring_base_tls/apidocs/argfile
?? spring_base_tls/apidocs/options

$ git status --short

$ git status --short
```

**Comment by TheSnoozer** [comment]
Hello, thanks for reporting this problem here and for taking your time to collect all these pointers.
Unfortunately I'm not even sure if there is a proper fix for this.

I currently don't understand how the javadoc-task would and could interfere with this plugin. In specific the jar-task should run with `package` (see https://maven.apache.org/plugins/maven-javadoc-plugin/jar-mojo.html). The revision-task of this plugin should run with the `initialize`-phase (as per [default config]( https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/master/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L52)). As per [Lifecycle Reference](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) those two phases should be far far apart....perhaps the `argfile` and `options` also created during the `initialize`-phase?! For a race-condition I somewhat would expect that the time the plugin asks for the state and the most recent state change are somewhat close (in the range of ns or ms), but usually builds run in the range of seconds or minutes (perhaps hours).

IMHO even trying to find out when those files are created would not fix the issue. The issue really boils down to a process (in this case javadoc generation) that puts (temporary)files into the git-directory. Even the non empty `git status -s` output you posted should be considered dirty - even if it's temporary. When this plugins happens to check in the exact moment when this is the case it IMHO rightfully reports a `dirty` state. When it happens to just check before or after that - the state should be reported as `non-dirty`.

Why does the java-plugin puts it's output into the git-repo and not the build directory? Default seems here `${project.build.directory}/apidocs`. Does it make a difference if you put those two files into the `.gitignore` (if there are more temporary files this makes this really ugly)?

**Comment by notes-jj** [comment]
I think I have to create a Minimal, Reproducible Example. I'm not even sure if javadoc-plugin is the reason. It's a large project with >10k Source Lines of Code. I'll try to do this by the weekend.

Could you advice how to set up logging, so I can see which files are "dirty"?

**Comment by TheSnoozer** [comment]
For debugging purposes I'd guess you could try using https://github.com/TheSnoozer/maven-git-commit-id-plugin.

For monitoring perhaps just an loop in bash/or windows cmd:
```
#!/bin/bash
while true
do
	echo "[$(date '+%Y-%m-%d %H:%M:%S')] git status -s"
        git status -s
	sleep 1
done
```
or
```
FOR /L %%A IN (1,1,200) DO (
  ECHO "[%date%-%time%] git status -s"
  git status -s
  timeout /t 1
)
```

You could also run this from any location by specifying the `-C <path>` option or `--git-dir=<path> --work-tree=<path>` option (see https://git-scm.com/docs/git#Documentation/git.txt--Cltpathgt)

**Comment by TheSnoozer** [comment]
Did you had the chance to troubleshoot this one further?
I still would claim that this is a race condition and the `maven-javadoc-plugin` should not place generated files into the source directory...

**Comment by TheSnoozer** [comment]
I'm going ahead and close this, since l think it is not an issue (or more or less a race-condition). feel free to reopen if you disagree.
