### ISSUE TITLE
Wrong git.remote.origin.url

### ISSUE THREAD

**Issue by spencergoff** [git-commit-id/git-commit-id-maven-plugin#442]
Hi, I was debugging a private project and I noticed that the value of git.remote.origin.url was not what I expected in several cases. Can someone please inform me where exactly this value gets set so I can debug?

**Comment by TheSnoozer** [comment]
Hello,
thank you for opening your issue here.
Where the information comes from depends how you configured `<useNativeGit>false</useNativeGit>`. Essentially the plugin allows to run with the native git binary or a java git implementation (`jgit`). When the switch is not set or `<useNativeGit>false</useNativeGit>`, the plugin uses the java git implementation (`jgit`).


For `jgit`:
https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/master/src/main/java/pl/project13/maven/git/JGitProvider.java#L222

For actual implementation details:
I believe this uses the [FileBasedConfig](https://github.com/eclipse/jgit/blob/009e07882fee2b0ad2ebe7ba44e2ff52c101f858/org.eclipse.jgit/src/org/eclipse/jgit/storage/file/FileBasedConfig.java#) which then delegates the call to the [Cofig](https://github.com/eclipse/jgit/blob/009e07882fee2b0ad2ebe7ba44e2ff52c101f858/org.eclipse.jgit/src/org/eclipse/jgit/lib/Config.java#L434) classes.


For `native git binary` we run `git ls-remote --get-url`:
https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/d7ad0f89e7880254f5aa93d3dbe9394a98a52c76/src/main/java/pl/project13/maven/git/NativeGitProvider.java#L312


Could you perhaps test if it makes any difference if you run with `<useNativeGit>false</useNativeGit>` or `<useNativeGit>true</useNativeGit>`?

You can manually check the URLs via `git ls-remote --get-url` or  `git remote -v`.
How does this differ from the produced output. Could you perhaps share obfuscated if there is any difference (e.g. simply replace usernames with JohnDoe and urls with example.com, projectnames with whatever)?

**Comment by TheSnoozer** [comment]
Could you verify if the plugin is misbehaving?

**Comment by TheSnoozer** [comment]
Feel free to reopen if still relevant or if you can reproduce the issue.
