### ISSUE TITLE
not creating git.properties in reactor build

### ISSUE THREAD

**Issue by delanym** [git-commit-id/git-commit-id-maven-plugin#467]
In a reactor build, the plugin doesn't even execute once (it doesn't create the git.properties file) when runOnlyOnce=false. But it does when true, and it does for a normal build when false.

```xml
<plugin>
  <groupId>pl.project13.maven</groupId>
  <artifactId>git-commit-id-plugin</artifactId>
  <version>4.0.0</version>
  <executions>
    <execution>
      <goals>
        <goal>revision</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <useNativeGit>true</useNativeGit>
    <offline>true</offline>
    <dateFormat>yyyyMMddHHmm</dateFormat>
    <dotGitDirectory>${project.basedir}/../.git</dotGitDirectory>
    <skipPoms>false</skipPoms>
    <generateGitPropertiesFile>true</generateGitPropertiesFile>
    <generateGitPropertiesFilename>${project.basedir}/../git.properties</generateGitPropertiesFilename>
    <failOnNoGitDirectory>true</failOnNoGitDirectory>
    <abbrevLength>7</abbrevLength>
    <runOnlyOnce>false</runOnlyOnce>
    <includeOnlyProperties>
      <includeOnlyProperty>^git.branch$</includeOnlyProperty>
      <includeOnlyProperty>^git.commit.id$</includeOnlyProperty>
      <includeOnlyProperty>^git.commit.time$</includeOnlyProperty>
    </includeOnlyProperties>
  </configuration>
</plugin>
```

git version 2.24.0
Apache Maven 3.6.0
openjdk version "1.8.0_232"
Ubuntu 19.04 \n \l
zsh 5.5.1 (x86_64-ubuntu-linux-gnu)

**Comment by delanym** [comment]
For some context, it was working (recreating the git.properties file) before I changed <offline>true</offline> to try speed things up, according to #462

**Comment by TheSnoozer** [comment]
hello,
thank you for reporting your issue here.
I tried to reproduce your issue with a demo project (https://github.com/TheSnoozer/git-commit-id-debugging/).

Based on your description and path's mentioned inside your configuration I would assume that the configuration is stored in a submodule. When I add the exact config to `submodule-one`  I can see the module being executed:
```
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ submodule-one ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
```

Try to add `<verbose>true</verbose>` which should give you a clear output on what is going on.

It might be that nothing has changed since the last execution and thus no re-generation of the properties is needed:
```
[INFO] --- git-commit-id-plugin:4.0.0:revision (default) @ submodule-one ---
[INFO] dotGitDirectory ..../workspace/git-commit-id-debugging/submodule-one/../.git
[INFO] Collected git.branch with value testing
[INFO] Collected git.commit.id with value beef4e92e9cabd043b105a14514289f331b40bf2
[INFO] Collected git.commit.time with value 201908252103
[INFO] including property git.commit.id in results
[INFO] including property git.commit.time in results
[INFO] including property git.branch in results
[INFO] Reading existing properties file [..../workspace/git-commit-id-debugging/submodule-one/../git.properties] (for module submodule-one)...
[INFO] Properties file [..../workspace/git-commit-id-debugging/submodule-one/../git.properties] is up-to-date (for module submodule-one)...
```

However in both cases the plugin checks if the properties file exists and seems to generate it accordingly.

If you still can not get it working, please demonstrate the issue by using a fork of https://github.com/TheSnoozer/git-commit-id-debugging/

**Comment by TheSnoozer** [comment]
Please reopen, if you can provide a project where I have chance to reproduce the issue.
