### ISSUE TITLE
support mojo properties

### ISSUE THREAD

**Issue by davidkarlsen** [git-commit-id/git-commit-id-maven-plugin#470]
### Describe your idea
Use https://maven.apache.org/plugin-tools/maven-plugin-annotations/apidocs/org/apache/maven/plugins/annotations/Parameter.html#property-- so that one can more easily override parameters in child-pom's / on command line.

### Expected Behavior
Today you can only configure plugin explicitly in an xml section, making it harder to parameterize behaviour.

### Additional context
See other maven plugins for inspiration, for instance surefire.

**Comment by TheSnoozer** [comment]
Hello,
thank you for this suggestion.
However i think this is something I would not explore further in this project.

Essentially this plugin has two major switches that work from command-line right now:
- [maven.gitcommitid.nativegit]https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/61af1b513246ebe629b9b5407fa8e85dbea37cdf/maven/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L228-L236)
- [maven.gitcommitid.skip](https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/61af1b513246ebe629b9b5407fa8e85dbea37cdf/maven/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L248-L260)

The ugly part of using properties is that the configuration within the XML always overwrites whatever is provided via command-line. IMHO maven should work in a way where the command-line argument should overwrite whatever is configured in the XML. So just adding 'property' is counter intuitive.
The "solution" to get this working as 'expected' from the plugin side is two essentially introduce two variables, one for the configuration for the XML and one for the command-line.

This is related to https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/315 and https://issues.apache.org/jira/browse/MNG-6278. Basically the maven maintainers consider this expected behaviour and if you want any other configuration exposed as configuration you should be able to follow the 'standard' way by specifying properties and using them inside the config:
```
<properties>
  <maven.gitcommitid.someprefix>blah-blub</maven.gitcommitid.someprefix>
</properties>
...
<plugin>
						<groupId>pl.project13.maven</groupId>
						<artifactId>git-commit-id-plugin</artifactId>
						<version>${git-commit-id-version}</version>
						<executions>
							<execution>
								<id>get-the-git-infos</id>
								<goals>
									<goal>revision</goal>
								</goals>
								<phase>initialize</phase>
							</execution>
						</executions>
						<configuration>
							<prefix>${maven.gitcommitid.someprefix}</prefix>
                                               </configuration>
</plugin>
```
