### ISSUE TITLE
Prevent header timestamp in git.properties to allow for reproducible builds

### ISSUE THREAD

**Issue by jrivard** [git-commit-id/git-commit-id-maven-plugin#472]
New feature: Prevent header timestamp in git.properties to allow for reproducible builds.

The git.properties file output includes the current time as a timestamp in a commented header.  This prevents reproducible builds because each build will include a different timestamp.

A feature fix would prevent this timestamp from being written as a comment header.

Note1: For reproducible builds the $git.build.time parameter also needs to be excluded
Note2: Using json format is a workaround for this issue

For reference:

https://maven.apache.org/guides/mini/guide-reproducible-builds.html

p.s.  Thanks for the awesome plugin and especially the detailed configuration documentation!

**Comment by TheSnoozer** [comment]
Hello,
thank you for opening an issue here.

Could you perhaps elaborate a bit more how you build your application?

AFAIK this plugin attempts to only re-generate this property file if it is [out-of-sync](https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/61af1b513246ebe629b9b5407fa8e85dbea37cdf/core/src/main/java/pl/project13/core/PropertiesFileGenerator.java#L59). If you wipe out the build and rebuild, yes the file would have a new header. Strongly speaking that might violate the 'reproducible build' principle. However I would see many other scenarios where strongly speaking the source code does not change, but it might result in a different output of that properties-files.
Examples might include `git.build.time` / `git.commit.time` or even `git.commit.id` if you have used `git commit --amend`. You technically can have the same source code with different commits (e.g. use `git cherry-pick`). Hence a different commit does not mean you have different 'source'-code. However the file still would need to be regenerated....:P

Altogether, I would favour your argument and would agree that we should avoid this extra bit of unnecessary information. Maybe this would be a good enough argument to get rid of the [java properties](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#store-java.io.OutputStream-java.lang.String-), since it seems there is no option to exclude the generation of the header and we want the properties sorted. Both is already not the default behaviour of the underlying hashset implementation of the java properties class...

**Comment by jrivard** [comment]
@TheSnoozer indeed this happens when I do a 'clean' before a 'package', so it's when starting a build from scratch.  This is the essence of reproducible builds, the same binary should be made by builders on two different machines.   Since I'm adding git-commit-id-maven-plugin to my build, the assumption is that the same build source and same commit info together will produce a reproducible build. 

There's some discussion about dealing with properties here:

https://stackoverflow.com/questions/6184335/properties-store-suppress-timestamp-comment

There are many ways to resolve this, none of them elegant, hence I didn't suggest one :)

As I mentioned in the note the json format works fine as an alternative, I just have a personal preference for the properties format as it's a bit more human friendly.....

**Comment by TheSnoozer** [comment]
Thanks for the additional input :-)
I understood your use-case, but would argue that in some cases this plugin *must* generate a different property-file, even if you have the same 'source' code. Clearly those cases I outlined are edge-cases and hence I fully agree that the plugin should not include the additional time-stamp in the generated properties-file.

Thanks for sharing the stackoverflow article more publicly -- I found this one too before commenting ;-)

Yeah...one can think generating and reading a file is easy, but this plugin suffers a similar pain with the json-properties (e.g. CVEs in the jackson library).

I'll try to look into fixing this and a general alternative for json processing too.
Sadly i won't have time for another month for active maintenance of this project, but I can happily review MRs ;-)
