### ISSUE TITLE
[Question] Run plugin with running project in IDEA

### ISSUE THREAD

**Issue by Tsyklop** [git-commit-id/git-commit-id-maven-plugin#474]
How I can run this plugin when I run my application in IDEA?

My configuration:
```
                      <plugin>
                        <groupId>pl.project13.maven</groupId>
                        <artifactId>git-commit-id-plugin</artifactId>
                        <version>${git-commit-id-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>compile</id>
                                <phase>compile</phase>
                            </execution>
                            <execution>
                                <id>get-the-git-infos</id>
                                <phase>validate</phase>
                                <goals>
                                    <goal>revision</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
                            <prefix>git</prefix>
                            <verbose>true</verbose>
                            <offline>false</offline>
                            <injectAllReactorProjects>true</injectAllReactorProjects>
                            <generateGitPropertiesFile>true</generateGitPropertiesFile>
                            <failOnUnableToExtractRepoInfo>true</failOnUnableToExtractRepoInfo>
                        </configuration>
                    </plugin>

```

**Comment by TheSnoozer** [comment]
Hello,
thank you for opening an issue for this.

Since IntelliJ seems to only be able to run the predefined [Maven Build Lifecycle](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) it seems you only can run this plugin from IntelliJ when its part of such a Build Lifecycle (e.g. `package`).

For testing I have used the debugging project:
https://github.com/TheSnoozer/git-commit-id-debugging/

On the right hand side, open the `Maven`-Tab, for my project I needed to activate the profile `git-with-parent` that includes the plugin and it's config and the simply right click on the `package` Lifecycle and `Run Maven Build`. 

![Selection_2020-03-07_18-49-29](https://user-images.githubusercontent.com/6849390/76150079-b114f600-60a6-11ea-8de4-8e3923829372.png)


PS: I don't even know if there would be a better/smarter way to inject this plugin into IntelliJ...in the end of the day this project is a maven plugin and not an IntelliJ plugin....

**Comment by TheSnoozer** [comment]
Closing as answered. If you still have a question feel free to reopen.

**Comment by wh81752** [comment]
Is there any way that this plugin `git-commit-id-plugin` is executed automatically when doing ''Build Project" (or Rebuild Project)??

**Comment by TheSnoozer** [comment]
Not sure, I have opened https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/602 to check (in general it's always better to open new issues instead of commenting on old ones).
