### ISSUE TITLE
git.build.user.mail can't be written to jar file

### ISSUE THREAD

**Issue by utekau** [git-commit-id/git-commit-id-maven-plugin#476]
Hi,

We were using this plugin for a long time. Starting from this week, when we generate our jar files, we can't set the user's mail to jar file. It was working fine and we haven't changed any configuration.

The command we run is simply "mvn clean package".

```
	<build>
		<finalName>${project.artifactId}-${git.commit.id.describe}-${git.build.user.mail}</finalName>
                        ....
			<plugin>
				<groupId>pl.project13.maven</groupId>
				<artifactId>git-commit-id-plugin</artifactId>
				<version>2.2.4</version>
				<executions>
					<execution>
						<id>get-the-git-infos</id>
						<goals>
							<goal>revision</goal>
						</goals>
						<phase>validate</phase>
					</execution>
				</executions>
				<configuration>
					<dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
				</configuration>
			</plugin>
```

Sample output is like that: xyz-backend-0e9e895-${git.build.user.mail}.jar

The thing is that I'm able to see my username, my mail etc during the packaging process. I can see found property messages. However, the output is lack of my mail information.

Java version: 1.8.0.241
Maven version: 3.5.2
Plugin version: 2.2.4

Thanks.

**Comment by TheSnoozer** [comment]
Hi,
thanks for creating an issue for this.

Since it appears this has worked before and now suddenly stopped working I wonder what has changed....have you perhaps changed your maven version? your java version?

Regardless the `finalName` should be a *readonly* parameter since version 3.0.0 (see https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12317526&version=12334171 or https://issues.apache.org/jira/browse/MJAR-217). So if it worked before I truly wonder how.....might just be related to https://issues.apache.org/jira/browse/MJAR-264 that it happened to work...I don't know....regardless in short Maven is not designed for dynamic versions and whenever you try to specify a dynamic version you'll need to apply endless workarounds. This is certainly not a limitation of this plugin, but of maven in general. You might be able to get away with the https://www.mojohaus.org/flatten-maven-plugin/usage.html.


Related:
* https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/maven/docs/faq.md#generated-properties-are-not-being-used-in-install-andor-deploy (or https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/256#issuecomment-321476196)
* https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/468
* https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/461

Where I outlined and explored the issue that might come with dynamic versions in more depth...

**Comment by utekau** [comment]
Hi,
Finally we had a chance to look at to issue again and realized that git.build.user.email tag written wrongly as git.build.user.mail :)

So, there wasn't any problem related the plugin, we made a mistake in pom.xml.

Thanks.
