### ISSUE TITLE
get-the-git-infos inside Maven package phase works a bit too late

### ISSUE THREAD

**Issue by jkosternl** [git-commit-id/git-commit-id-maven-plugin#530]
### Describe the bug
When using the execution of `<id>get-the-git-infos</id>` with on purpose delaying the generation of the `git.properties` file in the package phase, like: `<phase>package</phase>` then the file is correctly generated, but a little too late.. Just after Maven has wrapped all files together in a jar file.

### Steps to Reproduce
- just run a: `mvn clean package` using the specific setting:  `<phase>package</phase>`

```xml
<plugin>
	<groupId>pl.project13.maven</groupId>
	<artifactId>git-commit-id-plugin</artifactId>
	<version>4.0.3</version>
	<executions>
		<execution>
			<id>get-the-git-infos</id>
			<goals>
				<goal>revision</goal>
			</goals>
			<phase>package</phase>
		</execution>
	</executions>
	<configuration>
		<generateGitPropertiesFile>true</generateGitPropertiesFile>
		<useNativeGit>true</useNativeGit>
		<offline>true</offline>
		<generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties
		</generateGitPropertiesFilename>
		<format>json</format>
		<gitDescribe>
			<always>false</always>
		</gitDescribe>
		<offline>true</offline>
		<useNativeGit>true</useNativeGit>
	</configuration>
</plugin>
```

Then the Maven output is:
```
[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ orders ---
[INFO] Building jar: target\orders-0.1.0-SNAPSHOT.jar
[INFO]
[INFO] --- spring-boot-maven-plugin:2.2.10.RELEASE:repackage (default) @ orders ---
[INFO] Replacing main artifact with repackaged archive
[INFO]
[INFO] --- git-commit-id-plugin:4.0.3:revision (get-the-git-infos) @ orders ---
```
as you can see, it generates the file just after the orders.jar is created. 

I also tried with: `<phase>test</phase>` and than it works fine, because then the file is there, just before packaging the jar. 

- Is there a (public) project where this issue can be reproduced? No.
- Include any stack-traces or any error messages: No errors etc.

### Expected behavior
It would be great if we could make the build order inside the package phase a bit different. 

### Additional context
For reproducibility please provide the following:
- Java version "1.8.0_251"
- the plugin version: 4.0.3
- Apache Maven 3.6.3 
- Windows 10
- tested inside a Git Bash terminal
- how maven is being executed: ``mvn clean package``

**Comment by jkosternl** [comment]
Mmm, I just found out that `<phase>prepare-package</phase>` also works to change this order.. 
So, is it a good idea to change the order inside package, or just leave it and use `prepare-package` instead? Maybe we should put this in the notes!

**Comment by TheSnoozer** [comment]
Hello,
thank you for creating an issue for this. 
By default the `get-the-git-infos` should run with the `initialize`-phase (as documented on https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/maven/docs/using-the-plugin.md). Per maven's [lifecycle reference](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#lifecycle-reference) the `package` phase is described as `take the compiled code and package it in its distributable format, such as a JAR.`. From my understand that essentially means take everything that is there and bundle it in a distributable format. What you outline is IMHO matching with the existing documentation and indeed it would be too late to add any further information to the distributable format at this stage. That it perhaps makes less sense to run the  `get-the-git-infos` in such phase is up to the developer (you) to decide. It may make a lot of sense to have the plugin run in the `verify`-phase to validate that the git repository is in a specific state (e.g. on a tag). 

Please feel free to create a MR to improve the documentation (of the plugin), besides that I don't think there is anything else that I can do (since its the expected behaviour).
