### ISSUE TITLE
Maybe a bug working with Eclipse 2020-06

### ISSUE THREAD

**Issue by phantomjinx** [git-commit-id/git-commit-id-maven-plugin#531]
### Describe the bug
Import [project](https://github.com/syndesisio/syndesis/tree/1.11.x) and while building internally with maven-commit-id 4.0.0+ as a dependency, the following error appears in the Problem view. If I scale back to using the 3.0.1 version in the parent [pom](https://github.com/syndesisio/syndesis/blob/1.11.x/app/pom.xml#L117), the error no longer occurs. Also, there are no errors if the maven build is executed on the CLI.

- Is it an incompatibility in Eclipse or M2E with version 4.0.0+?
- Should the project have migrated specifically any configuration settings from versions 3 to 4?

```
Description	Resource	Path	Location	Type
Execution basepom.default of goal pl.project13.maven:git-commit-id-plugin:4.0.1:revision failed. (pl.project13.maven:git-commit-id-plugin:4.0.1:revision:basepom.default:initialize)

org.apache.maven.plugin.PluginExecutionException: Execution basepom.default of goal pl.project13.maven:git-commit-id-plugin:4.0.1:revision failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:332)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1379)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	.... .... ...
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:427)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 30 more
	pom.xml	/connector-ftp	line 19	Maven Build Problem
```

### Steps to Reproduce
- Import syndesis project into eclipse and start to auto-build

- configuration ([here]|(https://github.com/syndesisio/syndesis/blob/1.11.x/app/pom.xml#L1085)):
```
        <plugin>
          <groupId>pl.project13.maven</groupId>
          <artifactId>git-commit-id-plugin</artifactId>
          <version>${dep.plugin.git-commit-id.version}</version>
          <configuration>
            <injectAllReactorProjects>true</injectAllReactorProjects>
            <offline>true</offline>
            <runOnlyOnce>true</runOnlyOnce>
            <skipPoms>false</skipPoms>
            <useNativeGit>true</useNativeGit>
          </configuration>
        </plugin>
```

### Expected behavior
- No errors in eclipse.

### Additional context
For reproducibility please provide the following:
- Java 1.8.0
- Eclipse M2E 1.16.0
- Linux
- Eclipse auto-build using M2E

**Comment by TheSnoozer** [comment]
Hello,
thanks for reporting! Indeed that looks kinda like a bug in the plugin. 

Based on the details provided the issue appears to appear when running `session.getProjectDependencyGraph().getSortedProjects()` in [this line](https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/v4.0.1/maven/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L427). Now either `session` or `session.getProjectDependencyGraph()` could be `null` leading to the `NullPointerException`.

My gut feeling tells me that it might be the `session`-object which should be initialized [here](https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/v4.0.1/maven/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L81). Now what makes me a little suspicious is that the majority of variables is initialized via `defaultValue = "${....}"` while for the session the plugin plainly states `property = "session"`. Perhaps this also needs to be set via `defaultValue = "${....}"`? Not sure.


So far the import is still running on my end and the error didn't pop up yet....while I try to reproduce the issue, could you perhaps validate if this is also an issue with the latest plugin version (e.g. setting `<dep.plugin.git-commit-id.version>4.0.3</dep.plugin.git-commit-id.version>`). Is this reproducible on various machines, or just a single instance?

**Comment by phantomjinx** [comment]
Hey,
So I can confirm it still fails using 4.0.3. To help with debugging, I've cut 'n pasted out the relevant mvn sections and added them to a new project (see attached). Hopefully, you should be able to load this into eclipse pretty easily and see if this fails for you too.

[git-commit-id-issue.tar.gz](https://github.com/git-commit-id/git-commit-id-maven-plugin/files/5590122/git-commit-id-issue.tar.gz)

**Comment by TheSnoozer** [comment]
Thanks for the minimalistic example! I'm now (finally) able to reproduce the issue with the sample project.

Environment:
```
$ java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

$ grep -m 1 VERSION /etc/os-release
VERSION="18.04.5 LTS (Bionic Beaver)"

Eclipse DSL Tools (includes Incubating components)

Version: 2020-09 (4.17.0)
Build id: 20200910-1200
```

**Comment by TheSnoozer** [comment]
Thanks again for the tiny project that allowed to reproduce the issue.

After some troubleshooting it turns out that it doesn't seem to make a difference if we specify `@Parameter(property = 'session', ...)` VS a `@Parameter(defaultValue = '${session}')`.

The underlying issue that causes the `NullPointerException` is that `session.getProjectDependencyGraph()` is null. Why exactly this is the case is somewhat unclear. A reasonable guess is that this might be the case because we run the plugin via maven's plugin prefix resolution (e.g. via `pl.project13.maven:git-commit-id-plugin:4.0.1:revision:basepom.default:initialize`). Unfortunately this means it is impossible to find out if this plugin was executed before. As a result it this patch might defeat the point of `runOnlyOnce`. If eclipse runs the plugin multiple times for multiple projects I honestly don't know how we could avoid the multiple execution. 

Furthermore it appears that the [sonar-scanner-maven plugin]( https://github.com/SonarSource/sonar-scanner-maven/blob/45a6de3be55aed9fe2f8431a778022705b6067e6/src/main/java/org/sonarsource/scanner/maven/SonarQubeMojo.java#L134) that inspired the functionality is not effected by the same issue. A wild guess why the sonar-scanner-maven plugin might not be effected by this problem is that it uses a newer maven-plugin-api. Updating that would automatically drop the support for older maven versions....well the patch sounds reasonable so let me stop assuming any more weird maven things.
