### ISSUE TITLE
Different license?

### ISSUE THREAD

**Issue by Tockra** [git-commit-id/git-commit-id-maven-plugin#543]
### Describe your idea
The LGPL license isn't really clear in java context. I read a lot about it and found a lot of companies, which don't deliver java software with LGPL licensed stuff, because the law isn't clear.

I want to use this repo in a commercial project, but I will implement it myself now. 
Maybe other people have the same problem.

### Expected Behavior
Using the software in commercial projects without thinking about complicated law stuff...

### Additional context
I don't understand the idea of the benefits of the current license.

**Comment by TheSnoozer** [comment]
Hi,
thanks for creating an issue for this.
This project was initially started with the 'GNU Lesser General Public License v3.0' and the license has never changed.

Just to note: github gives you pretty indication what is allowed with/under the license (https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/LICENSE) and the GPLv3 allows you to use it for "Commercial use". Certainly I'm not a lawyer, but my reading of this is that you should be allowed to use the maven plugin in a commercial setup. 

You lost me at "I'm not using it because complicated law stuff". What else do you suggest? No license at all? Should we also get rid of laws of the world because "too complicated"? What would be a better license? The "Apache License 2.0", "MIT License", or "GPL-2"? How are they less "complicated"?

Just by scanning through some major open source projects you will notice that every project has some sort of license:
- https://github.com/apache/maven/blob/master/LICENSE -- Apache License 2.0
- https://github.com/google/guava/blob/master/COPYING -- Apache License 2.0
- https://github.com/python/cpython/blob/master/LICENSE -- Python Software Foundation License Version 2
- https://github.com/microsoft/vscode/blob/master/LICENSE.txt -- MIT License
- https://github.com/torvalds/linux/blob/master/COPYING -- GPL-2.0
- https://github.com/git/git/blob/master/COPYING -- GPL-2.0
- https://github.com/eclipse/jgit/blob/master/LICENSE --  Eclipse Distribution License v1.0

IMHO changing the license now would be tricky since every developer who ever contributed might need to give her/his ok to this license change. Feel free to implement anything yourself -- I don't hold you up. However in the end of the day I would guess that you end up using git and maven. As above that would mean that even the custom solution would need to consider the "Apache License 2.0" (for maven) and the "GPL-2.0 License" (for git).

**Comment by Tockra** [comment]
Every post about LGPL begins with a disclaimer. So this license can't be simple...
I searched at so many pages and it isn't clear what you need to do, when you want to develop a commercial java application with an LGPL licensed repository...

**Comment by Tockra** [comment]
Okay then not. But I'm still thinking that the LGPL license isn't a good choice for java programms ...
