### ISSUE TITLE
Separate build directory per branch

### ISSUE THREAD

**Issue by arpit-pp** [git-commit-id/git-commit-id-maven-plugin#551]
Is it possible to use a different project.build.directory for each branch with the help of this plugin?
I know it can be done by changing project.build.directory statically / by passing -D arg. 

I'm hoping something like this should work.

```xml
<build>
    <directory>${project.basedir}/target/${git.branch}</directory>
</build>
```

This works fine when run with `mvn compile -Dgit.branch=b1`.
 But it fails with compilation error when used with the plugin.

My plugin config:
```xml
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>4.0.0</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
                <configuration>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
                    <injectAllReactorProjects>true</injectAllReactorProjects>
                    <failOnNoGitDirectory>false</failOnNoGitDirectory>
                    <offline>true</offline>
                    <runOnlyOnce>true</runOnlyOnce>
                    <skipPoms>false</skipPoms>
                </configuration>
            </plugin>
```

**Comment by TheSnoozer** [comment]
Hello,
thank you for creating this issue and sorry for the late response.
Let me start that I honestly don't know if such approach would work. In principle I would have expected that the `git.branch` variable would be exposed to the pom when setting `<injectAllReactorProjects>true</injectAllReactorProjects>`. However I believe the build directory might be evaluated before the plugin is running. When the plugin is executed the git.branch` variable would be exposed, but the build directory doesn't get reset / overwritten potentially resulting in the fact that the build directory doesn't result in the expected.


What you still could try is to run the plugin in the `validation` phase, but that might result in the same problem.
You could also try your luck with using replacement properties, by adding the following to your pom:
```
<replacementProperties>
  <replacementProperty>
    <property>project.build.directory</property>
    <value>${project.basedir}/target/${git.branch}</value>
    <forceValueEvaluation>true</forceValueEvaluation>
</replacementProperties>
```
A potential more reliable way might even be using the https://github.com/mojohaus/flatten-maven-plugin that generates a new pom with all variables (hopefully) correctly resolved.

Another alternative might be to write a small wrapper script that exports the current branch as environment variable so it becomes available to maven's system environment variables.

Altogether it feels what you want to achieve here is not intended by maven. Or at least the current design doesn't really easily support what you are asking for. Since this plugin is operating in the maven world it is bound to whatever maven allows. In some sense I would even argue that it is not the intention to have multiple output/build directories per branch. What should happen if you run a `clean` for example? Should all build directories be wiped away, or just the one you are currently working on? What happens if the branch doesn't exist anymore and you don't run a clean? That would create a lot of waste on your computer that manually needs to be deleted....Anyhow I'm not here to argue that you might not need what you are asking. What I'm saying is that I doubt that maven allows such behaviour and thus I can't really help you with your request. 

I hope I still could give some hints on what you could try to get what you need.

Closing as won't fix.

**Comment by arpit-pp** [comment]
Thanks a lot for the detailed response @TheSnoozer 
Yeah, after looking a lot into ways to do this, I agree that this is not something that can be supported without hacks.

The problem I'm facing right now is when working on multiple branches, the maven caching doesn't work very optimally and I'm often left with NoClassDefFound errors, which make me run a clean compile.
Ideal behaviour I think would be to have the `clean` job clean only the target of current branch. And some other command which cleans targets compiled more than say 30 days ago.

This is what I've settled with, atleast for now. Works fine with one caveat. I have to keep `.mvn` directory in `.gitignore`.

post-checkout (git hook):
```bash
#!/bin/bash

set -e

checkoutType=$3

if [ "$checkoutType" != '1' ]; then
  # echo 'git checkout did not checkout a branch - quitting';
  exit;
fi

echo 'Executing post-checkout hook...';

ref_name="$(git symbolic-ref --short -q HEAD \
  || git describe --tags --exact-match 2> /dev/null \
  || git rev-parse --short HEAD)";

safe_ref_name="$(echo "$ref_name" | sed -E 's/[^[:alnum:]]+/-/g')";

echo "New ref: $safe_ref_name";

# Git seems to set $PWD as the directory containing .git
mvn_config_dir="$PWD/.mvn"
mvn_config_file="$mvn_config_dir/maven.config"
if [ -f "$mvn_config_file" ]; then
  sed -E "s/-Dgit.ref=[[:alnum:]-]+/-Dgit.ref=$safe_ref_name/g" "$mvn_config_file" | tee "$mvn_config_file" >/dev/null
else
  mkdir -p "$mvn_config_dir";
  echo "-Dgit.ref=$safe_ref_name" > "$mvn_config_file";
fi;
```

```xml
<property>
    <git.ref />
</property>
<build>
    <directory>${project.basedir}/target/${git.ref}</directory>
</build>
```
