### ISSUE TITLE
Time in ISO 8601 format

### ISSUE THREAD

**Issue by genieyr** [git-commit-id/git-commit-id-maven-plugin#575]
### Existed
git.build.time, git.commit.author.time, etc missed colon between offset time _2021-10-28T17:32:39+**0100**_
### Expected
It would be much better to provide time according java.time.format.ISO_OFFSET_DATE_TIME
such as 2011-10-28T17:32:39+01:00  to allow in Spring
``    @Value("${git.commit.author.time}") ``         
``    private OffsetDateTime commitDateTime;``

**Comment by TheSnoozer** [comment]
Hi,
thanks for creating this ticket.
By default the plugin will set the time-format to [`yyyy-MM-dd'T'HH:mm:ssZ`](
https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/ddb5f35e27642044fc5995da776da8b8a3f00ce8/src/main/java/pl/project13/maven/git/GitCommitIdMojo.java#L177) the date is then formatted by [simpledateformat](https://github.com/git-commit-id/git-commit-id-plugin-core/blob/0941938881ed21954aab74fb6918b24224309b2d/src/main/java/pl/project13/core/GitDataProvider.java#L380)


From https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC:
- Negative UTC offsets describe a time zone west of UTC±00:00, where the civil time is behind (or earlier) than UTC so the zone designator will look like "−03:00","−0300", or "−03".
- Positive UTC offsets describe a time zone at or east of UTC±00:00, where the civil time is the same as or ahead (or later) than UTC so the zone designator will look like "+02:00","+0200", or "+02".

From https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#patterns
- Z       zone-offset                 offset-Z          +0000; -0800; -08:00;

From http://www.loc.gov/standards/datetime/iso-tc154-wg5_n0038_iso_wd_8601-1_2016-02-16.pdf
Page 20, section "4.2.5.2 Local time and the difference from UTC" and Page 21 section "4.3.2 Complete representations"
also indicate that format "-08:00" and "-0800" are interchangeable. 

if you still want something different you can overwrite the format in the plugin config:
```
<dateFormat>yyyy-MM-dd G</dateFormat>
```

**Comment by genieyr** [comment]
yyyy-MM-dd'T'HH:mm:ssZ means RFC 822(without colon) not ISO 8601, from java.text.SimpleDateFormat javadoc
``` Z Time zone RFC  822  time zone -0800```
```X  Time zone ISO 8601 time zone -08; -0800; -08:00```
Perhaps you may change default format to  _yyyy-MM-dd'T'HH:mm:ssXXX_
Anyway, I've got expected  behavior by adding
```        
<configuration>
          <dateFormat>yyyy-MM-dd'T'HH:mm:ssXXX</dateFormat>
``` 
git.build.time=2021-11-02T11\:50\:17+01\:00
Thanks for the explanation.

**Comment by TheSnoozer** [comment]
Thanks for your input and keeping me in check!
Indeed the [SimpleDateFormat javadoc](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html) points out the difference.

I only can remember that the plugin adopted the timestamp formatting from maven itself. It seems to have changed some [time ago](https://github.com/apache/maven/commit/be19ddb6d92a6162c0b0cd0673f94dd5f570282b#diff-d706cd4e598b8b69cc978b677e39ab7f2ec0e0fc29b99605382f59a6afecafdc).

As of now the [CLIReportingUtils](https://github.com/apache/maven/blob/712199a004663ef15d6cffb19fa2e87dbe2a02fa/maven-embedder/src/main/java/org/apache/maven/cli/CLIReportingUtils.java#L164) is using `yyyy-MM-dd'T'HH:mm:ssXXX` and the [MavenBuildTimestamp](https://github.com/apache/maven/blob/712199a004663ef15d6cffb19fa2e87dbe2a02fa/maven-model-builder/src/main/java/org/apache/maven/model/interpolation/MavenBuildTimestamp.java#L34) is using `yyyy-MM-dd'T'HH:mm:ss'Z'`.

I guess from the plugin perspective it is fine to stick with the current variant, since similar to `MavenBuildTimestamp` the plugin is also generating timestamp output. Clearly I won't be able to find a default time-stamp formatting that would satisfy everyone so I guess I'll close the ticket as "won't fix" since it feels easy enough to adjust the format to what the individual requires.

Thanks for reporting :-)
