### ISSUE TITLE
5.0.0 doesn't seem to work with java 19

### ISSUE THREAD

**Issue by FrostNixon** [git-commit-id/git-commit-id-maven-plugin#600]
### Describe the bug
Upgraded from the old version 2.2.4 to the new 5.0.0 and moved to java 19 and maven 3.9.0, however now the git.commit and other properties are no longer resolved

### Steps to Reproduce
Simply update to java 19 and the new plugin and it no longer resolves any of the properties specified in the documentation.

### Expected behavior
Properties should continue to be available

**Comment by TheSnoozer** [comment]
Could you perhaps share the configuration of the plugin?

**Comment by FrostNixon** [comment]
`
            <plugin>
                <groupId>io.github.git-commit-id</groupId>
                <artifactId>git-commit-id-maven-plugin</artifactId>
                <version>5.0.0</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <verbose>true</verbose>
                    <injectAllReactorProjects>true</injectAllReactorProjects>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
                    <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
                    <skipPoms>false</skipPoms>
                    <dateFormat>yyyyMMddHHmmss</dateFormat>
                    <commitIdGenerationMode>full</commitIdGenerationMode>
                </configuration>
            </plugin>`

And my config is
`
<proeprties>
    <revision>${git.commit.time}.${git.branch}.${git.commit.id.abbrev}</revision>
</properties>
`

And im trying to build the project but it doesnt seem to be able to import the properties
`
    <groupId>com.groupid</groupId>
    <artifactId>parent-id</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
`

But then the build fails because it cant import it:
'parent-id${git.commit.time}.${git.branch}.${git.commit.id.abbrev}.pom'

**Comment by TheSnoozer** [comment]
I feel this is unrelated to java and more to the update of maven.
I bet when you run your build maven complains 24/7 that there are unresolved variables in your pom-project.

What you try to achieve here somewhat reminds me of https://github.com/git-commit-id/git-commit-id-maven-plugin/pull/444.

Essentially what I believe is happening is that maven loads the pom and populates the properties like `revision` with the unresolved variables. Now when the plugin is executed it would make `${git.commit.time}` and co available but unfortunately that doesn't trigger an update of the properties value like `revision`  which would then still have the unresolved variables.

Two potential workarounds:
1) Instead of using properties maybe try:
```xml
<groupId>com.groupid</groupId>
    <artifactId>parent-id</artifactId>
    <version>${git.commit.time}.${git.branch}.${git.commit.id.abbrev}</version>
    <packaging>pom</packaging>
```

2) if you really want to stick with the current approach you could leverage the replacement properties mentioned in the MR above. Something along like
```xml
<replacementProperties>
   <replacementProperty>
      <property>revision</property>
      <token>^.*$</token>
      <value>${git.commit.time}.${git.branch}.${git.commit.id.abbrev}</value>
      <regex>false</regex>
      <forceValueEvaluation>true</forceValueEvaluation>
   </replacementProperty>
</replacementProperties>
```

For further verification that the plugin actually still works you could also plugin the good old `maven-antrun-plugin` with some `echo`(s) into your build process:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-antrun-plugin</artifactId>
    <version>1.8</version>
    <executions>
        <execution>
            <phase>package</phase>
            <configuration>
                <target>
                    <echo>===========================================================================</echo>
                    <echo>revision at runtime: ${git.commit.time}.${git.branch}.${git.commit.id.abbrev}</echo>
                </target>
            </configuration>
            <goals>
                <goal>run</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Hope that helps.

**Comment by TheSnoozer** [comment]
Closing with can't reproduce (and lack of response). Please open a new issue if you still have issues.
